apiVersion: v1
kind: Pod
metadata:
   name: tomcat
spec:
   containers:
   - name: tomcat
     image: tomcat
     ports:
       containerPort: 7500
     imagePullPolicy: Always
   - name: database
     Image: mongo
     Ports:
       containerPort: 7501
     imagePullPolicy: Always
